dbfilename redis_queue.rdb
dir /Users/crysosancher/Documents/Cryso/Thoughtins/ERP-NEXT/frappe-bench/config/pids
pidfile /Users/crysosancher/Documents/Cryso/Thoughtins/ERP-NEXT/frappe-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /Users/crysosancher/Documents/Cryso/Thoughtins/ERP-NEXT/frappe-bench/config/redis_queue.acl
